a1 =input('digite algo:')
print('O tipo primitivo desse valor é:', type(a1))
print('só tem espaço?', a1.isspace())
print('é um numero?', a1.isnumeric())
print('é alfabetico?', a1.isalpha())
print('é alfanumerico?', a1.isalnum())
print('esta em maiusculas?', a1.isupper())
print('esta em minusculas?', a1.islower())
print('esta capitalizada?', a1.istitle())